import './pages/index.css';
import './script/index.js';
// import './script/cards.js';
// import './script/api.js';
// import './script/modal.js';
// import './script/validate.js';
import './script/components/Api.js';
import './script/components/Card.js';
import './script/components/FormValidator.js';
import './script/components/Popup.js';
import './script/components/PopupWithForm.js';
import './script/components/PopupWithImage.js';
import './script/components/Section.js';
import './script/components/UserInfo.js';
import './script/utils/constants.js';